### ISSUE TITLE
How Much Time It Takes For Training?

### ISSUE THREAD

**Issue by itsarunstark** [SuperKogito/Voice-based-gender-recognition#6]
bro i a started run.py  and training stucks at PROCESSNG  TrainingData/males\m0004_us_m0004_00114.wav what should i do?

**Comment by SuperKogito** [comment]
based on the Travis automated tests, it shouldn't take more than 30 minutes. So you should make sure that you set-up your environment correctly, or try to run features-collection, training and testing separately to figure out, where is it getting stuck.
